/* Generated by Snowball 2.2.0 - https://snowballstem.org/ */

#ifdef __cplusplus
extern "C" {
#endif

extern PGDLLIMPORT struct SN_env * russian_KOI8_R_create_env(void);
extern PGDLLIMPORT void russian_KOI8_R_close_env(struct SN_env * z);

extern PGDLLIMPORT int russian_KOI8_R_stem(struct SN_env * z);

#ifdef __cplusplus
}
#endif

