/* Generated by Snowball 2.2.0 - https://snowballstem.org/ */

#ifdef __cplusplus
extern "C" {
#endif

extern PGDLLIMPORT struct SN_env * irish_ISO_8859_1_create_env(void);
extern PGDLLIMPORT void irish_ISO_8859_1_close_env(struct SN_env * z);

extern PGDLLIMPORT int irish_ISO_8859_1_stem(struct SN_env * z);

#ifdef __cplusplus
}
#endif

