/* Generated by Snowball 2.2.0 - https://snowballstem.org/ */

#ifdef __cplusplus
extern "C" {
#endif

extern PGDLLIMPORT struct SN_env * romanian_ISO_8859_2_create_env(void);
extern PGDLLIMPORT void romanian_ISO_8859_2_close_env(struct SN_env * z);

extern PGDLLIMPORT int romanian_ISO_8859_2_stem(struct SN_env * z);

#ifdef __cplusplus
}
#endif

