/* Generated by Snowball 2.2.0 - https://snowballstem.org/ */

#ifdef __cplusplus
extern "C" {
#endif

extern PGDLLIMPORT struct SN_env * nepali_UTF_8_create_env(void);
extern PGDLLIMPORT void nepali_UTF_8_close_env(struct SN_env * z);

extern PGDLLIMPORT int nepali_UTF_8_stem(struct SN_env * z);

#ifdef __cplusplus
}
#endif

